module com {
module example {
module idl {
module messaging {

	struct Channel {
		long id;
		string name;
		string description;
	};

	struct User {
		long id;
		string name;
	};

	struct Message {
		long messageId;
		long channelId;
		long userId;
		string text;
	};
	
};
};
};
};