module com {
module example {
module idl {
module messaging {

    struct Channel {
        // @key
        long id;
        string name;
        string description;
    };

    struct User {
        // @key
        long id;
        string name;
    };

    struct Message {
        // @key
        long messageId;
        // @key
        long channelId;
        long userId;
        string text;
    };

};
};
};
};